fix(userscripts/qute-bitwarden): force username as empty string
In case login does not have a username or it is empty, this patch force
it to be an empty string. It avoids the following error:
```
Process stderr:
request_key: Required key not available
Traceback (most recent call last):
  File "/usr/share/qutebrowser/userscripts/qute-bitwarden", line 309, in <module>
    sys.exit(main(arguments))
             ~~~~^^^^^^^^^^^
  File "/usr/share/qutebrowser/userscripts/qute-bitwarden", line 244, in main
    choices = ['{:s} | {:s}'.format(c['name'], c['login']['username']) for c in candidates]
               ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported format string passed to NoneType.__format__
```